#title           :docker-compose.yml
#description     :Docker Compose file to deploy de KloudSense System
#author          :Alejandro Villegas Lopez (avillegas@keedio.com).
#===============================================================================




#===============================================================================
# KloudSense
#===============================================================================
version: '3.2'

services:
  grafana:
    image: keedio/ks-grafana-dcos:0.1-beta
    restart: on-failure
    container_name: ks-dcos-grafana
    hostname: ks-dcos-grafana
    ports:
      - "80:3000"
    networks:
      ks_net:
        ipv4_address: 172.16.1.1
    extra_hosts:
      - "prometheus:172.16.2.1"
    volumes:
      - type: bind
        source: ../dcos/grafana/grafana.ini
        target: /etc/grafana/grafana.ini
    labels:
      - "kloudsense.mode=DCOS"
      - "kloudsense.type=frontend"




  prometheus:
    image: keedio/ks-prometheus:0.2-beta
    restart: on-failure
    container_name: ks-dcos-prometheus
    hostname: ks-dcos-prometheus
    ports:
      - "60000:9090"
    networks:
      ks_net:
        ipv4_address: 172.16.2.1
    depends_on:
      - grafana
    extra_hosts:
      - "prometheus:172.16.2.1"
      - "grafana:172.16.1.1"
      - "alertmanager:172.16.4.1"
    volumes:
      - type: bind
        source: ../dcos/system/resolv.conf
        target: /etc/resolv.conf
      - type: bind
        source: ../dcos/prometheus/rules.yml
        target: /etc/prometheus/rules.yml
      - type: bind
        source: ../dcos/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus
    labels:
      - "kloudsense.mode=DCOS"
      - "kloudsense.type=short term storage"




  alertmanager:
    image: keedio/ks-alertmanager:0.2-beta
    restart: on-failure
    container_name: ks-dcos-alertmanager
    hostname: ks-dcos-alertmanager
    networks:
      ks_net:
        ipv4_address: 172.16.4.1
    depends_on:
      - prometheus
    ports:
      - "60100:9093"
    extra_hosts:
      - "prometheus:172.16.2.1"
    volumes:
      - type: bind
        source: ../dcos/alertmanager/alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    labels:
      - "kloudsense.mode=DCOS"
      - "kloudsense.type=alert management"





#=============================
# Networking
#===============================================================================
volumes:
  prometheus_data:




#=============================
# Networking
#===============================================================================
networks:
  ks_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          # SUBNETS
          # Front_End:
          #     172.16.1.XXX
          #
          # Prometheus:
          #     172.16.2.XXX
          #
          # Exporters:
          #     172.16.3.XXX
          #
          # Alert-Managers:
          #     172.16.4.XXX
          #
