#title           :docker-compose.yml
#description     :Docker Compose file to deploy de KloudSense System
#author          :Alejandro Villegas Lopez (avillegas@keedio.com).
#===============================================================================




#===============================================================================
# KloudSense
#===============================================================================
version: '3.2'

services:
  grafana:
    image: keedio/ks-grafana-dcos:0.1-beta
    restart: on-failure
    container_name: ks-dcos-grafana
    hostname: ks-dcos-grafana
    ports:
      - "80:3000"
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.1.1
    extra_hosts:
      - "prometheus:172.16.2.1"
    volumes:
      - type: bind
        source: ../dcos/grafana/grafana.ini
        target: /etc/grafana/grafana.ini
    healthcheck:
      test: ["CMD-SHELL", "curl -XGET http://localhost:3000/api/health | grep '\"database\": \"ok\"'"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  prometheus:
    image: keedio/ks-prometheus:0.2-beta
    restart: on-failure
    container_name: ks-dcos-prometheus
    hostname: ks-dcos-prometheus
    ports:
      - "60000:9090"
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.2.1
    depends_on:
      - grafana
    extra_hosts:
      - "prometheus:172.16.2.1"
      - "grafana:172.16.1.1"
      - "alertmanager:172.16.4.1"
      - "cp-adapter-read:172.16.2.2"
      - "cp-adapter-write:172.16.2.3"
    volumes:
      - type: bind
        source: ../dcos/system/resolv.conf
        target: /etc/resolv.conf
      - type: bind
        source: ../dcos/prometheus/rules.yml
        target: /etc/prometheus/rules.yml
      - type: bind
        source: ../dcos/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus
    healthcheck:
      test: ["CMD-SHELL", "[[ \"$$(wget -q -O - http://localhost:9090/-/healthy)\" == \"Prometheus is Healthy.\" ]]"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  cp-adapter-read:
    image: keedio/ks-cp-adapter:0.1.1-beta
    restart: on-failure
    container_name: ks-dcos-cp-adapter-read
    hostname: ks-dcos-cp-adapter-read
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.2.2
    depends_on:
      - prometheus
    extra_hosts:
      - "prometheus:172.16.2.1"
      - "cratedb-endpoint:172.16.6.0"
    volumes:
      - type: bind
        source: ../dcos/cp-adapter-read/config.yml
        target: /config.yml
    labels:
      - "kloudsense.mode=DCOS"


  cp-adapter-write:
    image: keedio/ks-cp-adapter:0.1.1-beta
    restart: on-failure
    container_name: ks-dcos-cp-adapte-writer
    hostname: ks-dcos-cp-adapte-writer
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.2.3
    depends_on:
      - prometheus
    extra_hosts:
      - "prometheus:172.16.2.1"
      - "cratedb-endpoint:172.16.6.0"
    volumes:
      - type: bind
        source: ../dcos/cp-adapter-write/config.yml
        target: /config.yml
    labels:
      - "kloudsense.mode=DCOS"


  cratedb-ce-node-load-balancer:
    image: keedio/ks-cratedb-ce:0.1.2-beta
    restart: on-failure
    container_name: ks-dcos-cratedb-ce-node-load-balancer
    hostname: ks-dcos-cratedb-ce-node-load-balancer
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.6.0
    depends_on:
      - cp-adapter-read
      - cp-adapter-write
    ports:
      - "4200:4200"
      - "5432:5432"
    volumes:
      - type: bind
        source: ../dcos/cratedb/node-load-balancer/crate.yml
        target: /crate-ce/config/crate.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://$$(hostname):4200 | grep '\"ok\" : true'"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  cratedb-ce-node-001:
    image: keedio/ks-cratedb-ce:0.1.2-beta
    restart: on-failure
    container_name: ks-dcos-cratedb-ce-node-001
    hostname: ks-dcos-cratedb-ce-node-001
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.6.1
    depends_on:
      - cratedb-ce-node-load-balancer
    ports:
      - "4201:4200"
    volumes:
      - type: bind
        source: ../dcos/cratedb/node-001/crate.yml
        target: /crate-ce/config/crate.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://$$(hostname):4200 | grep '\"ok\" : true'"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  cratedb-ce-node-002:
    image: keedio/ks-cratedb-ce:0.1.2-beta
    restart: on-failure
    container_name: ks-dcos-cratedb-ce-node-002
    hostname: ks-dcos-cratedb-ce-node-002
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.6.2
    depends_on:
      - cratedb-ce-node-load-balancer
    ports:
      - "4202:4200"
    volumes:
      - type: bind
        source: ../dcos/cratedb/node-002/crate.yml
        target: /crate-ce/config/crate.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://$$(hostname):4200 | grep '\"ok\" : true'"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  cratedb-ce-node-003:
    image: keedio/ks-cratedb-ce:0.1.2-beta
    restart: on-failure
    container_name: ks-dcos-cratedb-ce-node-003
    hostname: ks-dcos-cratedb-ce-node-003
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.6.3
    depends_on:
      - cratedb-ce-node-load-balancer
    ports:
      - "4203:4200"
    volumes:
      - type: bind
        source: ../dcos/cratedb/node-003/crate.yml
        target: /crate-ce/config/crate.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://$$(hostname):4200 | grep '\"ok\" : true'"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  alertmanager:
    image: keedio/ks-alertmanager:0.2-beta
    restart: on-failure
    container_name: ks-dcos-alertmanager
    hostname: ks-dcos-alertmanager
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.4.1
    depends_on:
      - prometheus
    ports:
      - "60100:9093"
    extra_hosts:
      - "prometheus:172.16.2.1"
    volumes:
      - type: bind
        source: ../dcos/alertmanager/alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    healthcheck:
      test: ["CMD-SHELL", "[[ \"$$(wget -q -O - http://localhost:9093/-/healthy)\" == \"OK\" ]]"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  airflow-redis:
    image: redis:3.2.7
    restart: on-failure
    container_name: ks-dcos-airflow-redis
    hostname: ks-dcos-airflow-redis
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.1
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  airflow-postgres:
    image: postgres:9.6
    restart: on-failure
    container_name: ks-dcos-airflow-postgres
    hostname: ks-dcos-airflow-postgres
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.2
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
        - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: airflow_pgsql_data
        target: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "kloudsense.mode=DCOS"


  airflow-webserver:
    image: keedio/ks-airflow:0.1-beta
    restart: on-failure
    container_name: ks-dcos-airflow-webserver
    hostname: ks-dcos-airflow-webserver
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.3
    depends_on:
      - airflow-postgres
      - airflow-redis
    ports:
      - "8083:8080"
    extra_hosts:
      - "postgres:172.16.7.2"
      - "redis:172.16.7.1"
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    volumes:
      - ../dcos/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"

  airflow-flower:
    image: keedio/ks-airflow:0.1-beta
    restart: on-failure
    container_name: ks-dcos-airflow-flower
    hostname: ks-dcos-airflow-flower
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.4
    depends_on:
      - airflow-redis
    extra_hosts:
      - "postgres:172.16.7.2"
      - "redis:172.16.7.1"
    environment:
      - EXECUTOR=Celery
      # - REDIS_PASSWORD=redispass
    ports:
      - "5555:5555"
    command: flower
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost:5555 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"

  airflow-scheduler:
    image: keedio/ks-airflow:0.1-beta
    restart: on-failure
    container_name: ks-dcos-airflow-scheduler
    hostname: ks-dcos-airflow-scheduler
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.5
    depends_on:
      - airflow-webserver
    extra_hosts:
      - "postgres:172.16.7.2"
      - "redis:172.16.7.1"
    ports:
      - "15555:5555"
      - "18080:8080"
      - "18793:8793"
    volumes:
      - ../dcos/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    command: scheduler
    labels:
      - "kloudsense.mode=DCOS"


  airflow-worker-001:
    image: keedio/ks-airflow:0.1-beta
    restart: on-failure
    container_name: ks-dcos-airflow-worker-001
    hostname: ks-dcos-airflow-worker-001
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.100
    depends_on:
      - airflow-scheduler
    extra_hosts:
      - "postgres:172.16.7.2"
      - "redis:172.16.7.1"
    volumes:
      - ../dcos/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    command: worker
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://$$(hostname):8793 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  airflow-worker-002:
    image: keedio/ks-airflow:0.1-beta
    restart: on-failure
    container_name: ks-dcos-airflow-worker-002
    hostname: ks-dcos-airflow-worker-002
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.101
    depends_on:
      - airflow-scheduler
    extra_hosts:
      - "postgres:172.16.7.2"
      - "redis:172.16.7.1"
    volumes:
      - ../dcos/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    command: worker
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://$$(hostname):8793 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"


  airflow-worker-003:
    image: keedio/ks-airflow:0.1-beta
    restart: on-failure
    container_name: ks-dcos-airflow-worker-003
    hostname: ks-dcos-airflow-worker-003
    networks:
      ks_dcos_net:
        ipv4_address: 172.16.7.102
    depends_on:
      - airflow-scheduler
    extra_hosts:
      - "postgres:172.16.7.2"
      - "redis:172.16.7.1"
    volumes:
      - ../dcos/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    command: worker
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://$$(hostname):8793 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "kloudsense.mode=DCOS"




#=============================
# Networking
#===============================================================================
volumes:
  prometheus_data:
  airflow_pgsql_data:




#=============================
# Networking
#===============================================================================
networks:
  ks_dcos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          # SUBNETS
          # Front_End:
          #     172.16.1.XXX
          #
          # Prometheus:
          #     172.16.2.XXX
          #
          # Exporters:
          #     172.16.3.XXX
          #
          # Alert-Managers:
          #     172.16.4.XXX
          #
          # CrateDB:
          #     172.16.6.XXX
          #
          # Airflow:
          #     172.16.7.XXX
