crate_endpoints:
- host: "cratedb-endpoint"    # Host to connect to (default: "localhost").
  port: 5432                  # Port to connect to (default: 5432).
  user: ""                    # Username to use (default: "crate")
  password: ""                # Password to use (default: "").
  schema: "prometheus"        # Schema to use (default: "").
  max_connections: 5          # The maximum number of concurrent connections (default: 5).
  enable_tls: false           # Whether to connect using TLS (default: false).
  allow_insecure_tls: false   # Whether to allow insecure / invalid TLS certificates (default: false).
