groups:
- name: CP-Adapters
  rules:
  - alert: Write errors on CrateDB
    expr: delta(crate_adapter_write_crate_failed_total[4m]) > 0
    for: 2m
    labels:
      severity: error
    annotations:
      summary: CrateDB insertion failed
