# My Global config
global:
  scrape_interval:     120s
  scrape_timeout:      110s
  evaluation_interval: 10s



# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "rules.yml"



scrape_configs:
  # Prometheus
  - job_name: 'DC/OS-Prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  # Grafana
  - job_name: 'DC/OS-Grafana'
    static_configs:
    - targets: ['grafana:3000']

  # Alertmanager
  - job_name: 'DC/OS-Alertmanager'
    static_configs:
    - targets: ['alertmanager:9093']

  # DC/OS Cluster
  - job_name: 'DC/OS-Metrics'
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - master.mesos
      - slave.mesos
      refresh_interval: 30s
      type: A
      port: 61091

remote_read:
   - url: http://cp-adapter-read:9268/read

remote_write:
   - url: http://cp-adapter-write:9268/write
